import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { SEOHead } from '@/components/SEOHead';
import { RelatedLinks } from '@/components/RelatedLinks';
import { getRelatedLinks } from '@/lib/internalLinks';
import { Link } from 'react-router-dom';

const Gitignore = () => (
  <div className="min-h-screen bg-background">
    <SEOHead
      title="The Perfect .gitignore for Every Stack (2026) | Zip2Git"
      description="Ready-to-copy .gitignore templates for Node, Python, React, Next.js, Django, Flutter, Unity, and more."
      path="/guides/gitignore"
      image="https://i.ibb.co/PGsmmHt8/7-zip2git.png"
    />
    <Navbar />
    <main className="container mx-auto px-4 py-6 sm:px-6 sm:py-10">
      <article className="mx-auto max-w-3xl space-y-6">
        <p className="text-sm text-primary">Guide · 4 min read</p>
        <h1 className="font-display text-4xl font-bold sm:text-5xl">
          The Perfect <span className="text-gradient">.gitignore</span> for Every Stack
        </h1>
        <p className="text-muted-foreground text-lg">
          A bad .gitignore wastes bandwidth, leaks secrets, and bloats your repo. Here are clean
          starter templates plus the rules every project should include.
        </p>

        <h2 className="font-display text-2xl font-bold pt-4">Universal Rules</h2>
        <pre className="bg-secondary/40 rounded-lg p-4 text-xs overflow-x-auto"><code>{`# Dependencies
node_modules/
vendor/
.venv/

# Env & secrets
.env
.env.*
*.pem
*.key

# Build output
dist/
build/
out/

# Editor
.vscode/
.idea/
.DS_Store
Thumbs.db`}</code></pre>

        <h2 className="font-display text-2xl font-bold pt-4">Node / React / Next.js</h2>
        <pre className="bg-secondary/40 rounded-lg p-4 text-xs overflow-x-auto"><code>{`node_modules/
.next/
.cache/
coverage/
npm-debug.log*
yarn-debug.log*
.pnpm-debug.log*`}</code></pre>

        <h2 className="font-display text-2xl font-bold pt-4">Python / Django / Flask</h2>
        <pre className="bg-secondary/40 rounded-lg p-4 text-xs overflow-x-auto"><code>{`__pycache__/
*.py[cod]
.venv/
venv/
*.egg-info/
.pytest_cache/
db.sqlite3`}</code></pre>

        <h2 className="font-display text-2xl font-bold pt-4">Mobile (Flutter / React Native)</h2>
        <pre className="bg-secondary/40 rounded-lg p-4 text-xs overflow-x-auto"><code>{`# Flutter
.dart_tool/
.packages
build/

# React Native
ios/Pods/
android/.gradle/
android/app/build/`}</code></pre>

        <h2 className="font-display text-2xl font-bold pt-4">Auto-Generated by Zip2Git</h2>
        <p className="text-muted-foreground leading-relaxed">
          When you push a ZIP via the <Link to="/" className="text-primary underline">Zip2Git converter</Link>,
          we detect your stack and generate a tailored .gitignore automatically. You can also use
          our standalone <Link to="/tools" className="text-primary underline">.gitignore generator</Link>{' '}
          in the developer toolkit.
        </p>

        <RelatedLinks links={getRelatedLinks('/guides/gitignore')} />
      </article>
    </main>
    <Footer />
  </div>
);

export default Gitignore;
